services:
 - type: web
   name: student-management-system-backend
   runtime: docker
   repo: https://github.com/Thavasiganesh/student-management
   plan: free
   region: singapore
   branch: main
   dockerContext: .
   dockerfilePath: Dockerfile
   envVars:
    - key: SPRING_PROFILES_ACTIVE
      value: prod 